# Netlify configuration file

# This tells Netlify how to build your frontend
[build]
  base    = "client"
  publish = "client/dist"
  command = "npm run build"

# This is the critical rule that fixes the "Page not found" error
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# This section fixes the new build error
[functions]
  directory = "server/functions"